# Palette
palette = "catppuccin_mocha"

# Format
format="""\
  $directory\
  $git_branch\
  $nodejs\
  $python\
  $git_status\
  $cmd_duration\
  \n$character
"""
add_newline = false

# Languages
[python]
format = "[]($style)[[ ](bg:base fg:yellow bold)$version](bg:base fg:yellow bold)[ ]($style)"
style = "bg:none fg:base"

[nodejs]
format = "[]($style)[[ ](bg:base fg:green bold)$version](bg:base fg:green bold)[ ]($style)"
style = "bg:none fg:base"

[docker_context]
symbol = " "

# Prompt symbols 
[character]
success_symbol = "[](green bold)"
error_symbol = "[](red bold)"
vicmd_symbol = "[](peach)"

[directory]
format = "[]($style)[ ](bg:base fg:yellow)[$path](bg:base fg:lavender bold)[ ]($style)"
style = "bg:none fg:base"
truncation_length = 3
truncation_symbol = "…/"
truncate_to_repo=false

[git_branch]
format = "[]($style)[[ ](bg:base fg:green bold)$branch](bg:base fg:lavender)[ ]($style)"
style = "bg:none fg:base"

[git_status]
format = "[]($style)[$all_status$ahead_behind](bg:base fg:yellow)[ ]($style)"
style = "bg:none fg:base"
conflicted = "="
ahead =	"⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
up_to_date = ""
untracked = "?${count}"
stashed = ""
modified = "!${count}"
staged = "+${count}"
renamed = "»${count}"
deleted = "${count}"

[cmd_duration]
min_time = 1
format = "[]($style)[[󰄉 ](bg:base fg:flamingo bold)$duration](bg:base fg:text)[ ]($style)"
disabled = false
style = "bg:none fg:base"

# Theme
[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"